# @name tokenacc
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "usuario": "guilherme"
    "pwd": "12345"
}

###

GET http://localhost:3000/usuario HTTP/1.1
x-access-token:{{tokenacc.response.body.token}}

###

POST http://localhost:3000/logout HTTP/1.1
Content-Type: application/json